<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="hexapod">
    <!-- Constants used throughout the model -->
    <xacro:property name="body_radius" value="0.5"/>
    <xacro:property name="leg_radius" value="0.2"/>
    <xacro:property name="segment_0_length" value="0.5"/>
    <xacro:property name="segment_1_length" value="1"/>
    <xacro:property name="segment_2_length" value="2"/>

    <!-- Some colors used throughout the model -->
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>
    
    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <material name="green">
        <color rgba="0 1 0 1"/>
    </material>
    
    <material name="blue">
        <color rgba="0 0 1 1"/>
    </material>

    <!-- The main body of the robot -->
    <link name="body">
        <visual>
            <geometry>
                <sphere radius="${body_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${body_radius}"/>
            </geometry>
        </collision>
    </link>

    <!-- Macro used to generate legs -->
    <xacro:macro name="leg" params="leg_id">
        <!-- First leg segment -->
        <link name="leg_${leg_id}_segment_0">
            <visual>
                <geometry>
                    <cylinder length="${segment_0_length}" radius="${leg_radius}"/>
                </geometry>
                <material name="blue"/>
                <origin xyz="0 0 ${segment_0_length/2}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${segment_0_length}" radius="${leg_radius}"/>
                </geometry>
                <origin xyz="0 0 ${segment_0_length/2}"/>
            </collision>
        </link>

        <!-- Joint connecting body to first leg segment -->
        <joint name="body_to_leg_${leg_id}_segment_0" type="revolute">
            <parent link="body"/>
            <child link="leg_${leg_id}_segment_0"/>
            <axis xyz="1 0 0"/>
            <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
            <!-- Determines the position and orientation of the leg based on its ID -->
            <origin xyz="${body_radius*sin(leg_id*pi/3)} ${body_radius*cos(leg_id*pi/3)} 0" rpy="0 ${pi/2} ${pi/2-leg_id*pi/3}"/>
        </joint>
    
        <!-- Second leg segment -->
        <link name="leg_${leg_id}_segment_1">
            <visual>
                <geometry>
                    <cylinder length="${segment_1_length}" radius="${leg_radius}"/>
                </geometry>
                <material name="red"/>
                <origin xyz="0 0 ${segment_1_length/2}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${segment_1_length}" radius="${leg_radius}"/>
                </geometry>
                <origin xyz="0 0 ${segment_1_length/2}"/>
            </collision>
        </link>

        <!-- Joint connecting first and second leg segments -->
        <joint name="leg_${leg_id}_segment_0_to_segment_1" type="revolute">
            <axis xyz="0 1 0"/>
            <parent link="leg_${leg_id}_segment_0"/>
            <child link="leg_${leg_id}_segment_1"/>
            <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
            <origin xyz="0 0 ${segment_1_length/2}"/>
        </joint>

        <!-- Third leg segment -->
        <link name="leg_${leg_id}_segment_2">
            <visual>
                <geometry>
                    <cylinder length="${segment_2_length}" radius="${leg_radius}"/>
                </geometry>
                <material name="green"/>
                <origin xyz="0 0 ${segment_2_length/2}"/>
            </visual>
            <collision>
                <geometry>
                    <cylinder length="${segment_2_length}" radius="${leg_radius}"/>
                </geometry>
                <origin xyz="0 0 ${segment_2_length/2}"/>
            </collision>
        </link>

        <!-- Joint connecting second and third leg segments -->
        <joint name="leg_${leg_id}_segment_1_to_segment_2" type="revolute">
            <axis xyz="0 1 0"/>
            <parent link="leg_${leg_id}_segment_1"/>
            <child link="leg_${leg_id}_segment_2"/>
            <limit effort="1000.0" lower="-0.5" upper="0.5" velocity="0.5"/>
            <origin xyz="0 0 ${segment_2_length/2}"/>
        </joint>

    </xacro:macro>

    <xacro:leg leg_id="0"/>
    <xacro:leg leg_id="1"/>
    <xacro:leg leg_id="2"/>
    <xacro:leg leg_id="3"/>
    <xacro:leg leg_id="4"/>
    <xacro:leg leg_id="5"/>
</robot>